### ISSUE TITLE
Otimizar fotos

### ISSUE THREAD

**Issue by brunont** [multas/sociais#4]
É necessário configurar e testar o paperclip para ele redimensionar automaticamente as fotos, pois atualmente ele mantém a foto no tamanho original, o que sobrecarrega a página e aumenta os custos de transferência do Amazon S3.

É necessário também manter compatibilidade com as fotos anteriores para não perder as fotos antigas.

**Comment by brunont** [comment]
Consegui configurar o ImageMagick aqui na minha máquina. Agora as fotos já estão subindo em 3 resoluções:
- original
- medium (largura 685px)
- small (largura 460px)

Dá para testar acessando as urls, neste exemplo:
Original: http://s3.amazonaws.com/msociais/fotos/761/original/IMG_0693.jpeg
Medium: http://s3.amazonaws.com/msociais/fotos/761/medium/IMG_0693.jpeg
Small: http://s3.amazonaws.com/msociais/fotos/761/small/IMG_0693.jpeg

Ou seja é só trocar ali na url para pegar os outros formatos.

O problema é que as fotos antigas não tem o seu correspondente /medium e /small

Tô vendo uma forma aqui de manter compatibilidade com as fotos anteriores...

**Comment by natanaelmaia** [comment]
Pq não cria uma rake task para percorrer todas as fotos anteriores e executar reprocess! ? Com isso você conseguiria gerar os correspondentes medium e small para das fotos antigas...

**Comment by natanaelmaia** [comment]
Você ainda poderia reduzir a qualidade do JPEG de alguma das resoluções (por exemplo a medium), da seguinte forma:

``` ruby
has_attached_file :foto,
  styles => { 
    :original => "1000x1000>",
    :medium => { :geometry => "685x685>", :convert_options => lambda {|f| "-quality 65%"}},
    :small => "460x460>"
  }
```
