### ISSUE TITLE
Ao criar nova multa via API é possível ignorar o atributo video, e isso causa a página da multa a não ser exibida (erro 500)

### ISSUE THREAD

**Issue by giggio** [multas/sociais#6]
Quando você submete uma nova multa, o video pode não ser enviado, o que faz com que no BD ele fique nulo. No entanto, quando isso acontece, a página da multa não é renderizada.
Veja exemplos do erro em produção:
http://multassociais.net/multas/750
http://multassociais.net/multas/750.json

A página da multa deve verificar se o video é nulo ou vazio, e não assumir que ele é vazio. Ou isso, ou a API deve exigir uma string vazia para o video, o que, IMO, não faz muito sentido. Além disso, essa mudança poderia quebrar apps existentes.

**Comment by giggio** [comment]
Em tempo, estou tendo que submeter uma string vazia na minha app, para evitar o problema, mas deveria ser resolvido no server.

**Comment by brunont** [comment]
opa, valeu giggio... solved ;-)

Links funcionando agora:
http://multassociais.net/multas/750
http://multassociais.net/multas/750.json
